### PR TITLE
Smelding is not a spell anymore

### PR DESCRIPTION
**Pull request by Mikeprod**

### CODE REVIEW

**Comment by Mikeprod** [comment]
I reopened this pull request, having however figured out that the toggle blocks any action from the spellbook, but not the skill itself for crafting professions.

**Comment by Mikeprod** [comment]
Closing temporarily this pull request until implementation following the Issue #14

**Comment by Mikeprod** [comment]
Added the clock fix #13 in the last commit, but more important the trade skill fix in the first commit answering #14

**Comment by MilleXIV** [comment]
Closing this as the rewrite invalidates. Switched to SecureActionButtonTemplate and using SpellBookItemName() to fetch the proper spell.

**Comment by Mikeprod** [comment]
Sry for reopening this but It does not work on non english clients ... with GetSpellBookItemName()

**Comment by MilleXIV** [comment]
Which language are you using? I've just tested in English and Spanish (EU) and it worked in both cases.

**Comment by Mikeprod** [comment]
My bad did not pull the right version :S

**Pull request closed without merging**
