### PR TITLE
Removed the Order Hall bar when databar on top & CC Text for bar & French Translation

### PR DESCRIPTION
**Pull request by Mikeprod**

### CODE REVIEW

**Comment by Mikeprod** [comment]
I have the following error with the last version : 
Message: Interface\AddOns\XIV_Databar\modules\talent.lua:154: unexpected symbol near 'local'
Time: 09/02/16 17:57:25
Count: 1
Stack: 
Locals:

**Comment by MilleXIV** [comment]
Edited on Github to fix that error you're getting. Otherwise this is an okay idea, but I'd rather add an option for the user to hide it instead of hiding it.

**Comment by Mikeprod** [comment]
I can add the option if I can save you the trouble

**Comment by Mikeprod** [comment]
I added the option. Known issue: order hall bar appears even if the option is checked to hide it if not disconnected in class hall. Missing a Refresh when entering the class hall

**Comment by Mikeprod** [comment]
Adding the class color option for the text

**Comment by Mikeprod** [comment]
Added French Translation

**Comment by Mikeprod** [comment]
I fixed the locale loading for the corresponding clients

**Comment by Mikeprod** [comment]
Moving all my improvements to the other pull request

**Pull request closed without merging**
